// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAXj4s3-409XIzn04FD23ykFzRPUakK3IE',
    appId: '1:9660359228:web:dcec09f22254a24d71d939',
    messagingSenderId: '9660359228',
    projectId: 'exam-ecommerce-app',
    authDomain: 'exam-ecommerce-app.firebaseapp.com',
    storageBucket: 'exam-ecommerce-app.appspot.com',
    measurementId: 'G-ZB1NFG97E3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAT3ffquRHz9KGq4HmwU5N2u9NbtD0QUlY',
    appId: '1:9660359228:android:eb8e79a14e65f20b71d939',
    messagingSenderId: '9660359228',
    projectId: 'exam-ecommerce-app',
    storageBucket: 'exam-ecommerce-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCmpnfrq-5Gd8s8YDwydTidMcdNGgIZi8w',
    appId: '1:9660359228:ios:f1d9bc8cb3b15bcb71d939',
    messagingSenderId: '9660359228',
    projectId: 'exam-ecommerce-app',
    storageBucket: 'exam-ecommerce-app.appspot.com',
    iosBundleId: 'com.example.rePr2Bhargav2344',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCmpnfrq-5Gd8s8YDwydTidMcdNGgIZi8w',
    appId: '1:9660359228:ios:a7cdc4552efb669b71d939',
    messagingSenderId: '9660359228',
    projectId: 'exam-ecommerce-app',
    storageBucket: 'exam-ecommerce-app.appspot.com',
    iosBundleId: 'com.example.rePr2Bhargav2344.RunnerTests',
  );
}
